# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开

# 使用主题
theme: indigo

# 网站定义
title: Kesa
subtitle: 大把时间迷茫 几个瞬间成长
description: All Day Dawn
keywords: Kesa
author: KesaubeEire
# email: your email
url: your site url

# Live2d宠物~赛高~
live2d:
  enable: true #是否允许出现
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    use: live2d-widget-model-shizuku #模型名称
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    width: 150
    height: 300
    position: right # 左侧还是右侧
    hOffset: 0
    vOffset: -20 # 离底部距离
  mobile:
    show: false # 手机客户端是否可见，推荐不可见，不然会影响阅读
    scale: 0.5
  react:
    opacityDefault: 0.7
    opacityOnHover: 0.2

deploy:
  type: git
  repo: git@github.com:jiji262/jiji262.github.io.git
  branch: master